baseURL       = "https://laserradesca.com/"
languageCode  = "en-us"
title         = "La Serradesca | Società agricola"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  # [[menu.nav]]
  #   name    = "Home"
  #   url     = ""
  #   weight  = 1
  [[menu.nav]]
    name    = "Chi Siamo"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Servizi"
    url     = "portfolio"
    weight  = 3
  # [[menu.nav]]
  #   name    = "Blog"
  #   url     = "blog"
  #   weight  = 4
  [[menu.nav]]
    name    = "Contattaci"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "La Serradesca | Società agricola"
  author = "Paolo Innocenti"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/f/meqndazp"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nome"
    placeholder_last_name         = "Cognome"
    placeholder_email             = "Email"
    placeholder_project_type      = "Interesse"
    placeholder_about_the_project = "Messaggio"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "f"
      title  = "Frutta"
    [[params.contactForm.projectType]]
      value = "v"
      title  = "Vino"
    [[params.contactForm.projectType]]
      value = "m"
      title  = "Miele"
    [[params.contactForm.projectType]]
      value = "z"
      title  = "Altro"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contattaci"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/cascina_main.jpg"
    heading               = "Siamo una società agricola che coltiva delle cose"
    tagline               = "WE WORK HARD, WE PLAY HARD"
    primary_button        = "La nostra offerta"
    primary_button_url    = "portfolio"
    secondary_button      = "Contattaci"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "La nostra offerta"
    subtitle  = "Quello che facciamo nella nostra azienda agricola."

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET'S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contatti"
      address = "località Casotto 1, 24020 Torre de' Roveri (BG)"
      phone   = "+39 342 6385086"
      email   = "info@laserradesca.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Chi siamo"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Servizi"
          url  = "portfolio"
        # [[params.footer.sitemap.link]]
        #   name = "Blog"
        #   url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contattaci"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        # [[params.footer.social.link]]
        #   name = "Medium"
        #   url  = "#"
        # [[params.footer.social.link]]
        #   name = "Behance"
        #   url  = "#"
        # [[params.footer.social.link]]
        #   name = "Dribbble"
        #   url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      # [params.footer.service]
      #   title       = "We help brands:"
      #   description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"